# Generated by Django 6.0 on 2026-01-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reboot_App', '0002_userprofile_email_otp_userprofile_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
